<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Contact</h1>
        <p>This is a web application which is designed to help you easily create and manage contact information pages.</p>
        <p>Here you will be able to:</p>
        <ul>
            <li>Create a new contact</li>
            <li>Modify an existing contact</li>
            <li>Delete an existing contact</li>
            <li>Search for a contact</li>
        </ul>
    </div>
</div>
<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <p>You can find the list of existing contacts by pushing the button below. "Modify" and "Delete" options are available for each existing contact. </p>
            <p><a class="btn btn-outline-secondary" href="/comp1230/assignment/cont/public/?page=persons&action=view" role="button">View contacts &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <p>You can add a new contact by simply pushing the button below and filling out the form. Make sure all mandatory fields are present when adding a contact.</p>
            <p><a class="btn btn-outline-secondary" href="/comp1230/assignment/cont/public/?page=persons&action=add" role="button">Add new contact &raquo;</a></p>
        </div>
    </div>
    <hr>
</div> <!-- /container -->
