<div class="jumbotron">
    <div class="container">
        <form action="/comp1230/assignment/cont/public/?page=persons&action=doAdd" method="post" enctype="multipart/form-data"
              id="needs-validation" novalidate>
            <div class="form-group">
                <label for="inputTitle">Job Title</label>
                <input type="text" name="jTitle" class="form-control" id="inputTitle" placeholder="Job Title" required>
                <div class="invalid-feedback">
                    Please provide a job title.
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputFName">First Name</label>
                    <input type="text" name="fName" class="form-control" id="inputFName" placeholder="First name" required>
                    <div class="invalid-feedback">
                        Please provide a first name.
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label for="inputLName">Last Name</label>
                    <input type="text" name="lName" class="form-control" id="inputLName" placeholder="Last name" required>
                    <div class="invalid-feedback">
                        Please provide a last Name.
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">E-mail</label>
                    <input type="text" name="email" class="form-control" id="inputEmail4" placeholder="E-mail">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputSite">Web Site</label>
                    <input type="text" name="site" class="form-control" id="inputSite" placeholder="Site">
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <label for="inputCellNumber">Cell Number</label>
                    <input type="text" name="cellNumber" class="form-control" id="inputCellNumber" placeholder="Cell Number">
                </div>
                <div class="col">
                    <label for="inputHomeNumber">Home Number</label>
                    <input type="text" name="homeNumber" class="form-control" id="inputHomeNumber" placeholder="Home Number">
                </div>
                <div class="col">
                    <label for="inputOfficeNumber">Office Number</label>
                    <input type="text" name="officeNumber" class="form-control" id="inputOfficeNumber" placeholder="Office Number">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputTwitterUrl">Twitter</label>
                    <input type="text" name="twitterUrl" class="form-control" id="inputTwitterUrl" placeholder="Twitter URL">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputFacebookUrl">Facebook</label>
                    <input type="text" name="facebookUrl" class="form-control" id="inputFacebookUrl" placeholder="Facebook URL">
                </div>
            </div>
            <div class="form-group">
            <label for="file1">Upload a picture</label><br>
            <label class="custom-file" for="file1">
                <input type="file" name="picture" id="file1" class="custom-file-input">

                <span class="custom-file-control"></span>
            </label>
            </div>
            <div class="form-group">
                <label for="comment">Comment</label>
                <textarea class="form-control" name="comment" id="comment" rows="1" cols="20" wrap="hard"></textarea>
            </div>
            <input type="hidden" name="id" value="<?php echo $added_person[0]; ?>">
            <input type="submit" name="submit" id="submit" class="btn btn-outline-secondary">
            <button type="button" class="btn btn-outline-secondary" onclick="goBack()">Go Back</button>
        </form>
    </div>
</div>
<script src="scripts.js"></script>